name: OWASP ZAP Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  security-events: write

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://www.hackthissite.org/'
          format: 'html,json'
          output: 'reports/'
          fail-on-warn: false
          
      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-security-report
          path: reports/
          retention-days: 30

      - name: Upload to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/report_json.sarif